export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECIEVE_PRODUCTS = 'RECIEVE_PRODUCTS';
export const LOWEST_TO_HIGHEST_PRODUCTS = 'LOWEST_TO_HIGHEST_PRODUCTS';
export const HIGHEST_TO_LOWEST_PRODUCTS = 'HIGHEST_TO_LOWEST_PRODUCTS';
