version: '2'

services:
  fairthreadsreactclient:
    build: app-service
    environment:
      - VIRTUAL_HOST=shopfairthreads.com
  nginx-proxy:
    build: custom-nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
