// -- Do not include in vendor bundle --
// 'extract-text-webpack-plugin',
// 'html-webpack-plugin',
// 'node-sass',

module.exports = [
  'classnames',
  'contentful',
  'isomorphic-fetch',
  'jquery',
  'morgan',
  'react',
  'react-addons-css-transition-group',
  'react-addons-shallow-compare',
  'react-autobind',
  'react-css-modules',
  'react-dom',
  'react-lazy-load',
  'react-redux',
  'react-router',
  'react-router-redux',
  'react-router-scroll',
  'react-slick',
  'react-waypoint',
  'redux',
  'redux-logger',
  'redux-seamless-immutable',
  'redux-thunk',
  'reselect',
  'seamless-immutable',
  'showdown',
  'slick-carousel',
];
