export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECIEVE_PRODUCTS = 'RECIEVE_PRODUCTS';
export const LOWEST_TO_HIGHEST_PRODUCTS = 'LOWEST_TO_HIGHEST_PRODUCTS';
export const HIGHEST_TO_LOWEST_PRODUCTS = 'HIGHEST_TO_LOWEST_PRODUCTS';
export const TOGGLE_SALE_ONLY = 'SHOW_SALE_ONLY';
export const SET_PRICE_RANGE_FILTER = 'SET_PRICE_RANGE_FILTER';
export const REMOVE_PRICE_RANGE_FILTER = 'REMOVE_PRICE_RANGE_FILTER';
